version: "3.8"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
      - xpack.security.enabled=false          # 로컬 개발용: 보안 OFF
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports:
    - "${ES_HTTP_PORT}:9200"
    - "${ES_TRANSPORT_PORT}:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-bridge
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
    - "${KIBANA_PORT}:5601"
    depends_on:
      es:
        condition: service_healthy
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge

volumes:
  es-data:
