name: CI-CD Deploy

on:
  push:
    branches: ["dev"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Network check (Maven Central)
        run: |
          set -eux
          curl -I https://repo.maven.apache.org/maven2/ | head -n 20
          curl -I https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.11.0/gson-2.11.0.pom | head -n 20

      - name: Build Project (skip tests)
        run: ./gradlew clean build -x test --info --stacktrace

      - name: Build Docker Image
        run: |
          docker build  -f Dockerfile_dev -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:dev .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:dev

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            echo "📦 최신 이미지 Pull"
            sudo docker compose pull

            echo "📦 기존 컨테이너 제거"
            docker compose down --rmi all --volumes
            
            echo "🚀 서비스 재시작"
            sudo docker compose up -d
      
            echo "🎉 DEV 배포 완료!"
